- name: Installing Nagios Dependencies and Libraries
  tags: dependencies, libraries
  yum:
    name:
      - gcc
      - glibc
      - glibc-common
      - perl
      - httpd
      - php
      - wget
      - gd
      - gd-devel
      - openssl-devel
      - gcc
      - glibc
      - glibc-common
      - make
      - gettext
      - automake
      - autoconf
      - wget
      - openssl-devel
      - net-snmp
      - net-snmp-utils
      - python2-pip
    state: latest

- name: Install passlib Python Package
  yum:
    name: python2-passlib
    state: present

- name: Creating a directory for the downloaded files
  file:
    path: ~/nagios
    state: directory

- name: Downloading and Extracting Nagios from Github
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777

- name: Adding Users and Groups, Compiling, and Installing in Nagios from Github
  shell:
    cd ~/nagios/nagioscore-**
    ./configure
    make all
    make install-groups-users
    usermod -a -G nagios apache
    make install
    make install-daemoninit
    make install-commandmode
    make install-config
    make install-webconf

- name: Downloading and Extracting Nagios plugins from Github
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Compiling and Installing Nagios plugins
  shell:
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install

- name: Setting User and Password
  community.general.htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: jrstendencia
    password: 1234567

- name: Confirmation of Nagios is enabled
  service:
    name: nagios
    state: restarted
    enabled: true

- name: Confirmation of httpd is enabled
  service:
    name: httpd
    state: restarted
    enabled: true
